sudo: required
dist: xenial
language: python
python:
  - '3.5'
virtualenv:
  system_site_packages: true
services:
  - xvfb
install:
  - sudo apt-get -y install python3-gi gir1.2-gtk-3.0
  - pip install --quiet -r ci/requirements.txt
  - git clone https://github.com/"${TRAVIS_REPO_SLUG%%/*}"/qubes-builder ~/qubes-builder
script:
  - PYTHONPATH=test-packages pylint qubes qubespolicy
  - ./run-tests --no-syslog
  - ~/qubes-builder/scripts/travis-build
env:
 - DIST_DOM0=fc25 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DIST_DOM0=fc29 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1

after_success:
  - codecov -F unittests
  - ~/qubes-builder/scripts/travis-deploy

# don't build tags which are meant for code signing only
branches:
  except:
    - /.*_.*/

addons:
  apt:
    packages:
      - debootstrap

# vim: ts=2 sts=2 sw=2 et
