import:
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-base-r4.0.yml
    mode: deep_merge_prepend
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-dom0-r4.0.yml
python:
  - '3.5'
virtualenv:
  system_site_packages: true
services:
  - xvfb
install:
  - sudo apt-get -y install python3-gi gir1.2-gtk-3.0
  - pip install --quiet -r ci/requirements.txt
  - git clone https://github.com/"${TRAVIS_REPO_SLUG%%/*}"/qubes-builder ~/qubes-builder
script:
  - PYTHONPATH=test-packages pylint qubes qubespolicy
  - ./run-tests
after_success:
  - codecov -F unittests
  - ~/qubes-builder/scripts/travis-deploy
addons:
  apt:
    packages:
      - debootstrap
